
Raw Benchmark Output
====================

Running Lattice Boltzmann D2Q9 on Octuplets using NumPy/CPU
    commit: `#88335e0b0a721a97d5d4977fc8a3d842f4626957 <https://bitbucket.org/bohrium/bohrium/commits/88335e0b0a721a97d5d4977fc8a3d842f4626957>`_,
    time: 2014-09-19 13:58:35.822246.

    command: ``python benchmark/Python/lattice_boltzmann_D2Q9.py --size=100*100*10 --bohrium=False``

Run 00
~~~~~~
    stdout::

        N/A

    stderr::

        Error in [cpu:impl]: /home/bhbuilder/.local/lib/libbh_ve_cpu.so: cannot open shared object file: No such file or directory
        terminate called after throwing an instance of 'std::runtime_error'
          what():  Error in the initialization of the VEM.
        
        



Run 01
~~~~~~
    stdout::

        N/A

    stderr::

        Error in [cpu:impl]: /home/bhbuilder/.local/lib/libbh_ve_cpu.so: cannot open shared object file: No such file or directory
        terminate called after throwing an instance of 'std::runtime_error'
          what():  Error in the initialization of the VEM.
        
        



Run 02
~~~~~~
    stdout::

        N/A

    stderr::

        Error in [cpu:impl]: /home/bhbuilder/.local/lib/libbh_ve_cpu.so: cannot open shared object file: No such file or directory
        terminate called after throwing an instance of 'std::runtime_error'
          what():  Error in the initialization of the VEM.
        
        



